# Generated by Django 3.2.7 on 2021-10-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_degree',
        ),
    ]
