# Generated by Django 3.2.5 on 2021-10-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_ecoinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
