# Generated by Django 3.2.5 on 2021-10-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211004_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ecological',
            new_name='is_eco',
        ),
    ]
