# Generated by Django 3.2.6 on 2021-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211014_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='1', max_length=120),
        ),
    ]
