# Generated by Django 3.2.5 on 2021-09-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
