# Generated by Django 3.2.6 on 2021-10-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
