# Generated by Django 3.2.5 on 2021-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ecological',
            field=models.BooleanField(default=False),
        ),
    ]
